// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-h9aBj7AjAmspt6V5y89UneYTJb4GWoA',
    appId: '1:920461569916:web:35f66ca254b4e1411e7ef9',
    messagingSenderId: '920461569916',
    projectId: 'workmate-app-ff26d',
    authDomain: 'workmate-app-ff26d.firebaseapp.com',
    storageBucket: 'workmate-app-ff26d.firebasestorage.app',
    measurementId: 'G-JZLMDVWKXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHrvLIl9iVKwzk5PVoSj-MBd6czAAbOUU',
    appId: '1:920461569916:android:5f3b4d0a9a73bec91e7ef9',
    messagingSenderId: '920461569916',
    projectId: 'workmate-app-ff26d',
    storageBucket: 'workmate-app-ff26d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOx8zd_ZDN7gEzrA-lew_ItTv3st4TS7g',
    appId: '1:920461569916:ios:51e39b1d7f1630661e7ef9',
    messagingSenderId: '920461569916',
    projectId: 'workmate-app-ff26d',
    storageBucket: 'workmate-app-ff26d.firebasestorage.app',
    iosBundleId: 'com.example.workmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOx8zd_ZDN7gEzrA-lew_ItTv3st4TS7g',
    appId: '1:920461569916:ios:51e39b1d7f1630661e7ef9',
    messagingSenderId: '920461569916',
    projectId: 'workmate-app-ff26d',
    storageBucket: 'workmate-app-ff26d.firebasestorage.app',
    iosBundleId: 'com.example.workmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-h9aBj7AjAmspt6V5y89UneYTJb4GWoA',
    appId: '1:920461569916:web:1efb5577e6cbb63f1e7ef9',
    messagingSenderId: '920461569916',
    projectId: 'workmate-app-ff26d',
    authDomain: 'workmate-app-ff26d.firebaseapp.com',
    storageBucket: 'workmate-app-ff26d.firebasestorage.app',
    measurementId: 'G-BGSP2YC0BB',
  );
}
